---
# data collection configuration
sampling_timeout: 1
modules: [ "conv2d", "maxpooling2d", "linear", "activations" ]
module_configurations:
  # ----
  # Conv2d Module
  # ----
  conv2d:
    meta:
      # Attention: if False all possible combinations from module_params will be computed
      random_sampling: True
      # number of samples if random_sampling True
      sampling_cutoff: 100
      # number of times a config should be repeated
      num_repeat_config: 1
      # PyTorch's architectures to extract specific configurations from
      configs_from_architectures: [ 'alexnet','vgg11','vgg13','vgg16' ]
      # the path to the location where the data-file should be saved
      output_path: "./data/conv2d-energies-raw.csv"
    module_params:
      # parameter: range[from,to,by]
      batch_size: [ 1,257,1 ]
      image_size: [ 4,225,1 ]
      kernel_size: [ 1,12,1 ]
      in_channels: [ 1,513,1 ]
      out_channels: [ 1,513,1 ]
      stride: [ 1,6,1 ]
      padding: [ 0,4,1 ]
  # ----
  # MaxPool2d Module
  # ----
  maxpooling2d:
    meta:
      random_sampling: True
      sampling_cutoff: 100
      num_repeat_config: 1
      configs_from_architectures: [ 'alexnet','vgg11','vgg13','vgg16' ]
      output_path: "./data/maxpooling2d-energies-raw.csv"
    module_params:
      batch_size: [ 1,257,1 ]
      image_size: [ 4,225,1 ]
      kernel_size: [ 1,12,1 ]
      in_channels: [ 1,513,1 ]
      stride: [ 1,6,1 ]
      padding: [ 0,4,1 ]
  # ----
  # Linear Module
  # ----
  linear:
    meta:
      random_sampling: True
      sampling_cutoff: 100
      num_repeat_config: 1
      configs_from_architectures: [ 'alexnet','vgg11','vgg13','vgg16' ]
      output_path: "./data/linear-energies-raw.csv"
    module_params:
      batch_size: [ 1,513,1 ]
      input_size: [ 1,5001,1 ]
      output_size: [ 1,5001,1 ]
  # ----
  # Activations Module
  # ----
  # TODO: make it possible to specify which activations to sample
  activations:
    meta:
      random_sampling: True
      # no. of samples for all activations in total i.e. 100 -> 25 per activation
      sampling_cutoff: 400
      num_repeat_config: 1
      configs_from_architectures: []
      output_path: "./data/activations-energies-raw.csv"
    module_params:
      batch_size: [ 1,513,1 ]
      input_size: [ 1,5001,1 ]