---
test_data_path: ''
estimation_to_compute:
  alexnet: 5
  vgg11: 16
  vgg13: 64
  vgg16: 256
model_configurations:
  conv2d:
    features_config:
      base_features: [ 'batch_size', 'image_size', 'kernel_size', 'in_channels', 'out_channels', 'stride', 'padding' ]
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  maxpool2d:
    features_config:
      base_features: [ 'batch_size','image_size','kernel_size','in_channels','stride','padding' ]
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  linear:
    features_config:
      base_features: [ 'batch_size','input_size','output_size' ]
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  relu:
    features_config:
      base_features: ['batch_size', 'input_size']
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  sigmoid:
    features_config:
      base_features: [ 'batch_size', 'input_size' ]
      enable_log_features: True
      enable_macs_feature: False
    model_version: ''
  softmax:
    features_config:
      base_features: [ 'batch_size', 'input_size' ]
      enable_log_features: True
      enable_macs_feature: False
    model_version: ''
  tanh:
    features_config:
      base_features: [ 'batch_size', 'input_size' ]
      enable_log_features: True
      enable_macs_feature: False
    model_version: ''

