---
test_data_path: ''
model_configurations:
  conv2d:
    features_config:
      base_features: [ 'in_channels','out_channels','image_size','image_height','padding','kernel_size','stride','batch_size' ]
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  maxpool2d:
    features_config:
      base_features: [ 'in_channels','image_size','image_height','padding','kernel_size','stride','batch_size' ]
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  linear:
    features_config:
      base_features: [ 'input_size', 'output_size', 'batch_size' ]
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''
  activations:
    features_config:
      base_features: ['input_size','batch_size']
      enable_log_features: True
      enable_macs_feature: True
    model_version: ''