---
test_data_path: ''
estimation_to_compute:
  #alexnet: 5
  #vgg11: 16
  #vgg13: 64
  vgg16: 256
# from current working directory
data_directory: '/data'


model_configurations:
  # feature configurations have to match the specified model version!
  # ----
  # Conv2d Module
  # ----
  conv2d:
    # chooses most recent version if unspecified
    model_version: ''
    data_file_name: 'conv2d-energies-parsed.csv'
    base_features: [ 'batch_size', 'image_size', 'kernel_size', 'in_channels', 'out_channels', 'stride', 'padding' ]
    features_config:
      enable_base_features: True
      enable_log_features: True
      enable_macs_feature: True
  # ----
  # MaxPool2d Module
  # ----
  maxpool2d:
    model_version: ''
    data_file_name: 'maxpool2d-energies-parsed.csv'
    base_features: [ 'batch_size','image_size','kernel_size','in_channels','stride','padding' ]
    features_config:
      enable_base_features: True
      enable_log_features: True
      enable_macs_feature: True
  # ----
  # Linear Module
  # ----
  linear:
    model_version: ''
    data_file_name: 'linear-energies-parsed.csv'
    base_features: [ 'batch_size','input_size','output_size' ]
    features_config:
      enable_base_features: False
      enable_log_features: False
      enable_macs_feature: True
  # ----
  # Activations
  # ----
  relu:
    model_version: ''
    data_file_name: 'relu-energies-parsed.csv'
    base_features: [ 'batch_size', 'input_size' ]
    features_config:
      enable_base_features: False
      enable_log_features: False
      enable_macs_feature: True
  sigmoid:
    model_version: ''
    data_file_name: 'sigmoid-energies-parsed.csv'
    base_features: [ 'batch_size', 'input_size' ]
    features_config:
      enable_base_features: True
      enable_log_features: False
      enable_macs_feature: False
  softmax:
    model_version: ''
    data_file_name: 'softmax-energies-parsed.csv'
    base_features: [ 'batch_size', 'input_size' ]
    features_config:
      enable_base_features: True
      enable_log_features: False
      enable_macs_feature: False
  tanh:
    model_version: ''
    data_file_name: 'tanh-energies-parsed.csv'
    base_features: [ 'batch_size', 'input_size' ]
    features_config:
      enable_base_features: True
      enable_log_features: False
      enable_macs_feature: False

